"""
Copies the engine's shared collector assets into the Chrome extension (MV3 cannot load code from outside
its own folder or from the network):

  aura/analyzers/js/dom_extraction.js -> extension/content/dom_extraction.js  (wrapped as a global function)
  aura/vendor/axe.min.js              -> extension/vendor/axe.min.js

Run after changing either source:   python -m aura.tools.sync_extension_assets
tests/test_extension_assets.py fails if the copies drift from the sources.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DOM_SOURCE = ROOT / "aura" / "analyzers" / "js" / "dom_extraction.js"
AXE_SOURCE = ROOT / "aura" / "vendor" / "axe.min.js"
EXT = ROOT / "extension"
DOM_TARGET = EXT / "content" / "dom_extraction.js"
AXE_TARGET = EXT / "vendor" / "axe.min.js"

DOM_HEADER = ("// GENERATED by `python -m aura.tools.sync_extension_assets` from aura/analyzers/js/dom_extraction.js.\n"
              "// Do not edit: the AURA engine and the extension must extract DOM evidence identically.\n")


def expected_dom_copy() -> str:
    return DOM_HEADER + "globalThis.__AURA_DOM_EXTRACT = " + DOM_SOURCE.read_text(encoding="utf-8").rstrip() + ";\n"


def sync() -> None:
    DOM_TARGET.parent.mkdir(parents=True, exist_ok=True)
    AXE_TARGET.parent.mkdir(parents=True, exist_ok=True)
    DOM_TARGET.write_text(expected_dom_copy(), encoding="utf-8", newline="\n")
    AXE_TARGET.write_bytes(AXE_SOURCE.read_bytes())
    make_icons()
    print(f"synced {DOM_TARGET.relative_to(ROOT)} and {AXE_TARGET.relative_to(ROOT)}")


def make_icons() -> None:
    """Simple AURA mark (violet rounded square, white ring + dot). Generated so no binary assets are hand-made."""
    try:
        from PIL import Image, ImageDraw
    except ImportError:
        return
    icons = EXT / "icons"
    icons.mkdir(exist_ok=True)
    for size in (16, 32, 48, 128):
        path = icons / f"icon{size}.png"
        if path.exists():
            continue
        s = size * 4
        img = Image.new("RGBA", (s, s), (0, 0, 0, 0))
        d = ImageDraw.Draw(img)
        d.rounded_rectangle([0, 0, s - 1, s - 1], radius=int(s * 0.22), fill=(109, 40, 217, 255))
        m, w = s * 0.2, max(4, int(s * 0.1))
        d.ellipse([m, m, s - m, s - m], outline=(255, 255, 255, 255), width=w)
        c, r = s / 2, s * 0.09
        d.ellipse([c - r, c - r, c + r, c + r], fill=(255, 255, 255, 255))
        img.resize((size, size), Image.LANCZOS).save(path)


if __name__ == "__main__":
    sync()
